[package]
name = "pgutils-migrate"
version = "0.0.0"
authors = ["Peter Frank <mdm23@gmx.de>"]
edition = "2021"

[dependencies]
lazy_static = "1.4"
proc-macro2 = "1.0"
quote = "1.0"
regex = "1"
sha2 = "0.10"
thiserror = "1.0"
tokio-postgres = "0.7"